export const SITE_NAVBAR = 'SITE_NAVBAR';
export const CART_SIDE_NAV = 'CART_SIDE_NAV';
export const WISH_SIDE_NAV = 'WISH_SIDE_NAV';


// Cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SIDE_BARS = 'SIDE_BARS';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const RESET_CART = 'RESET_CART';

// Product 
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";



// Wishlist
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';


// Compares
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';
export const REMOVE_FROM_COMPARE = 'REMOVE_FROM_COMPARE';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_PRODUCTION = 'GET_CATEGORY_PRODUCTION';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';


// User
export const GET_USER = 'GET_USER';
export const LOGIN = 'LOGIN';

// placement
export const PLACEMENT = 'PLACEMENT';
export const PLACEMENT_PRODUCTS = 'PLACEMENT_PRODUCTS';
export const PLACEMENT_METHOD = 'PLACEMENT_METHOD'
export const TOTAL_PRICE = 'TOTAL_PRICE';